/**
 * Seed script: creates 1 user, 20 communities, and 100 posts.
 * Run: npx tsx apps/api/src/scripts/seed.ts
 */
import 'dotenv/config';
import mongoose from 'mongoose';
import { env } from '../config/env.js';
import { User } from '../modules/users/user.model.js';
import { Community } from '../modules/communities/community.model.js';
import { Post } from '../modules/posts/post.model.js';
import { calculateHotScore } from '../utils/ranking.js';

const COMMUNITIES = [
  { name: 'javascript', displayName: 'JavaScript', description: 'All things JavaScript — ES6+, Node.js, frameworks, and beyond.', tags: ['javascript', 'web', 'frontend'] },
  { name: 'typescript', displayName: 'TypeScript', description: 'TypeScript tips, tricks, and discussion. Strong types, strong code.', tags: ['typescript', 'types', 'web'] },
  { name: 'python', displayName: 'Python', description: 'Python programming, data science, automation, and web development.', tags: ['python', 'datascience', 'backend'] },
  { name: 'rust', displayName: 'Rust', description: 'Memory-safe systems programming with Rust. Fearless concurrency!', tags: ['rust', 'systems', 'performance'] },
  { name: 'golang', displayName: 'Go', description: 'Go programming language — simple, reliable, efficient.', tags: ['go', 'backend', 'cloud'] },
  { name: 'react', displayName: 'React', description: 'React.js — component-driven UIs, hooks, Next.js, and the React ecosystem.', tags: ['react', 'frontend', 'javascript'] },
  { name: 'webdev', displayName: 'Web Development', description: 'General web development discussion — HTML, CSS, JS, frameworks, and tooling.', tags: ['web', 'frontend', 'backend'] },
  { name: 'devops', displayName: 'DevOps', description: 'CI/CD, Docker, Kubernetes, infrastructure as code, and cloud platforms.', tags: ['devops', 'cloud', 'docker'] },
  { name: 'linux', displayName: 'Linux', description: 'Linux distros, kernel, shell scripting, system administration.', tags: ['linux', 'os', 'sysadmin'] },
  { name: 'git_tips', displayName: 'Git Tips', description: 'Git workflows, tips, tricks, and version control best practices.', tags: ['git', 'tools', 'workflow'] },
  { name: 'databases', displayName: 'Databases', description: 'SQL, NoSQL, PostgreSQL, MongoDB, Redis — all database discussion.', tags: ['databases', 'sql', 'nosql'] },
  { name: 'algorithms', displayName: 'Algorithms', description: 'Data structures, algorithms, competitive programming, and interview prep.', tags: ['algorithms', 'dsa', 'interviews'] },
  { name: 'cpp', displayName: 'C++', description: 'Modern C++ discussion — C++17, C++20, templates, and performance.', tags: ['cpp', 'systems', 'performance'] },
  { name: 'java', displayName: 'Java', description: 'Java programming — Spring Boot, microservices, JVM ecosystem.', tags: ['java', 'backend', 'enterprise'] },
  { name: 'machinelearning', displayName: 'Machine Learning', description: 'ML, deep learning, neural networks, PyTorch, TensorFlow.', tags: ['ml', 'ai', 'datascience'] },
  { name: 'security', displayName: 'Security', description: 'Cybersecurity, pentesting, CTFs, secure coding practices.', tags: ['security', 'hacking', 'crypto'] },
  { name: 'opensource', displayName: 'Open Source', description: 'Open source projects, contributions, licensing, and community.', tags: ['opensource', 'community', 'github'] },
  { name: 'career', displayName: 'Dev Career', description: 'Career advice, job hunting, salary, interviews, and growth.', tags: ['career', 'jobs', 'interviews'] },
  { name: 'vim_emacs', displayName: 'Vim & Emacs', description: 'Text editor wars and productivity. Share your dotfiles!', tags: ['vim', 'emacs', 'tools'] },
  { name: 'mobile_dev', displayName: 'Mobile Dev', description: 'iOS, Android, React Native, Flutter — mobile development.', tags: ['mobile', 'ios', 'android'] },
];

const POSTS: Array<{ title: string; type: 'text' | 'link' | 'code'; body?: string; url?: string; codeSnippet?: { code: string; language: string; fileName?: string }; communityIdx: number }> = [
  // javascript (0)
  { title: 'Why I switched from CommonJS to ESM in 2025', type: 'text', body: 'After years of using require(), I finally migrated all my Node.js projects to native ESM. The transition was rough at first — jest configs broke, dynamic imports needed refactoring, and some packages still don\'t support it. But the benefits are worth it: tree shaking actually works, top-level await is a game changer, and the ecosystem is finally catching up. Here\'s what I learned...', communityIdx: 0 },
  { title: 'The new Set methods in JavaScript are amazing', type: 'text', body: 'Set.prototype.union(), intersection(), difference(), and symmetricDifference() are now available in all major browsers. No more lodash for set operations! These methods return new Sets and work with any iterable. The best part? They\'re incredibly fast compared to manual implementations using filter and includes.', communityIdx: 0 },
  { title: 'Promise.withResolvers() is underrated', type: 'code', codeSnippet: { code: '// Before - awkward pattern\nlet resolve, reject;\nconst promise = new Promise((res, rej) => {\n  resolve = res;\n  reject = rej;\n});\n\n// After - clean and readable\nconst { promise, resolve, reject } = Promise.withResolvers();\n\n// Great for event-based patterns\nfunction waitForEvent(emitter, event) {\n  const { promise, resolve } = Promise.withResolvers();\n  emitter.once(event, resolve);\n  return promise;\n}', language: 'javascript', fileName: 'promise-resolvers.js' }, communityIdx: 0 },
  { title: 'V8 just shipped a 40% improvement in regex performance', type: 'link', url: 'https://v8.dev/blog/regex-performance-2025', communityIdx: 0 },
  { title: 'Temporal API is finally shipping — goodbye moment.js', type: 'text', body: 'The Temporal API proposal has reached Stage 4 and Chrome 128 shipped it unflagged. This is the biggest improvement to date/time handling in JavaScript since... well, ever. Temporal.PlainDate, Temporal.ZonedDateTime, Temporal.Duration — they cover every use case that made us reach for moment.js or date-fns. The API is verbose but explicit, which I actually prefer.', communityIdx: 0 },

  // typescript (1)
  { title: 'Using const type parameters changed how I write generics', type: 'code', codeSnippet: { code: '// Without const - types widen\nfunction routes<T extends readonly string[]>(paths: T) {\n  return paths; // T is string[]\n}\n\n// With const - types are literal\nfunction routes<const T extends readonly string[]>(paths: T) {\n  return paths; // T is readonly [\"/home\", \"/about\"]\n}\n\nconst r = routes([\"/home\", \"/about\"]);\n// type: readonly [\"/home\", \"/about\"] ✅', language: 'typescript', fileName: 'const-type-params.ts' }, communityIdx: 1 },
  { title: 'TypeScript 5.6 released: iterator helpers, disallowed nulls in assignments', type: 'link', url: 'https://devblogs.microsoft.com/typescript/typescript-5-6', communityIdx: 1 },
  { title: 'Stop using enums, use const objects instead', type: 'code', codeSnippet: { code: '// ❌ Enums have quirks\nenum Status {\n  Active = "active",\n  Inactive = "inactive",\n}\n\n// ✅ Const objects are simpler and more predictable\nconst Status = {\n  Active: "active",\n  Inactive: "inactive",\n} as const;\n\ntype Status = (typeof Status)[keyof typeof Status];\n// type Status = "active" | "inactive"', language: 'typescript', fileName: 'no-enums.ts' }, communityIdx: 1 },
  { title: 'Branded types for type-safe IDs in TypeScript', type: 'text', body: 'Tired of accidentally passing a userId where a postId is expected? Branded types solve this without any runtime overhead. The idea is simple: use intersection types with a phantom brand property that only exists at the type level. TypeScript will catch the mismatch at compile time, but the value is just a plain string at runtime.', communityIdx: 1 },
  { title: 'My tsconfig.json for 2025 — strict, modern, fast', type: 'code', codeSnippet: { code: '{\n  "compilerOptions": {\n    "strict": true,\n    "target": "ES2024",\n    "module": "NodeNext",\n    "moduleResolution": "NodeNext",\n    "verbatimModuleSyntax": true,\n    "noUncheckedIndexedAccess": true,\n    "exactOptionalPropertyTypes": true,\n    "noPropertyAccessFromIndexSignature": true,\n    "isolatedDeclarations": true,\n    "erasableSyntaxOnly": true,\n    "skipLibCheck": true\n  }\n}', language: 'json', fileName: 'tsconfig.json' }, communityIdx: 1 },

  // python (2)
  { title: 'Python 3.13 free-threaded mode: first real benchmarks', type: 'text', body: 'I benchmarked Python 3.13 with the GIL disabled (--disable-gil) on a CPU-bound workload using 8 threads. Results: 5.2x speedup on a Fibonacci calculation, 3.8x on a matrix multiplication, and 6.1x on image processing. The per-thread overhead is about 10-15% compared to GIL-enabled single-threaded, but the parallelism makes up for it easily. This is the future of Python.', communityIdx: 2 },
  { title: 'uv is the future of Python packaging', type: 'text', body: 'If you haven\'t tried uv yet, you\'re missing out. It\'s a drop-in replacement for pip that\'s written in Rust and is 10-100x faster. `uv pip install` feels instant. It also handles virtual environments, lockfiles, and Python version management. I\'ve completely replaced pip, pip-tools, pyenv, and virtualenv with just uv.', communityIdx: 2 },
  { title: 'Pattern matching in Python is more powerful than you think', type: 'code', codeSnippet: { code: 'def handle_response(response):\n    match response:\n        case {"status": 200, "data": {"users": [first, *rest]}}:\n            print(f"First user: {first}, {len(rest)} more")\n        case {"status": 200, "data": {"users": []}}:\n            print("No users found")\n        case {"status": 404}:\n            print("Not found")\n        case {"status": status} if status >= 500:\n            print(f"Server error: {status}")\n        case _:\n            print("Unknown response")', language: 'python', fileName: 'pattern_matching.py' }, communityIdx: 2 },
  { title: 'A comprehensive guide to Python decorators', type: 'link', url: 'https://realpython.com/primer-on-python-decorators/', communityIdx: 2 },
  { title: 'FastAPI vs Django in 2025: when to use which', type: 'text', body: 'After building production APIs with both, here\'s my take: FastAPI for microservices, internal tools, and ML model serving. Django for anything with users, admin panels, or complex business logic. FastAPI is faster but Django\'s ecosystem (ORM, admin, auth, migrations) saves more development time in the long run. Both are excellent choices.', communityIdx: 2 },

  // rust (3)
  { title: 'I rewrote my Go microservice in Rust. Here\'s what happened.', type: 'text', body: 'Latency dropped from 12ms p99 to 800μs. Memory usage went from 120MB to 8MB. But it took 3x longer to write and the compile times are painful. For hot-path services that need raw performance, Rust is unbeatable. For everything else, I\'d still reach for Go. The Rust type system catches so many bugs at compile time though — zero runtime panics in 6 months of production.', communityIdx: 3 },
  { title: 'Error handling in Rust with thiserror and anyhow', type: 'code', codeSnippet: { code: 'use thiserror::Error;\n\n#[derive(Error, Debug)]\npub enum AppError {\n    #[error("database error: {0}")]\n    Database(#[from] sqlx::Error),\n    #[error("not found: {0}")]\n    NotFound(String),\n    #[error("unauthorized")]\n    Unauthorized,\n}\n\n// In library code: use thiserror for typed errors\n// In application code: use anyhow for ergonomic error handling\n\nuse anyhow::{Context, Result};\n\nasync fn get_user(id: i64) -> Result<User> {\n    let user = db.fetch_one(id)\n        .await\n        .context("failed to fetch user")?;\n    Ok(user)\n}', language: 'rust', fileName: 'errors.rs' }, communityIdx: 3 },
  { title: 'Rust 2024 edition: what changed and why it matters', type: 'link', url: 'https://doc.rust-lang.org/edition-guide/rust-2024/', communityIdx: 3 },
  { title: 'Async Rust is getting much easier with 2025 updates', type: 'text', body: 'With async closures stabilized, impl Trait in more positions, and the ongoing work on async iterators, the async Rust experience has improved dramatically. You no longer need Box::pin() everywhere, and the error messages have gotten so much better. Tokio 2.0 is also on the horizon with a simplified API.', communityIdx: 3 },
  { title: 'Blazingly fast CLI tool in 50 lines of Rust with clap', type: 'code', codeSnippet: { code: 'use clap::Parser;\nuse std::fs;\n\n#[derive(Parser)]\n#[command(name = \"loc\", about = \"Count lines of code\")]\nstruct Cli {\n    /// Path to count\n    path: String,\n    /// File extension filter\n    #[arg(short, long)]\n    ext: Option<String>,\n}\n\nfn main() {\n    let cli = Cli::parse();\n    let mut total = 0;\n    \n    for entry in walkdir::WalkDir::new(&cli.path)\n        .into_iter()\n        .filter_map(|e| e.ok())\n        .filter(|e| e.file_type().is_file())\n    {\n        if let Some(ref ext) = cli.ext {\n            if entry.path().extension().map_or(true, |e| e != ext.as_str()) {\n                continue;\n            }\n        }\n        if let Ok(content) = fs::read_to_string(entry.path()) {\n            total += content.lines().count();\n        }\n    }\n    println!(\"{total} lines\");\n}', language: 'rust', fileName: 'main.rs' }, communityIdx: 3 },

  // golang (4)
  { title: 'Go 1.23 iterator functions are a game changer', type: 'code', codeSnippet: { code: 'package main\n\nimport (\n    "fmt"\n    "iter"\n    "slices"\n)\n\nfunc Filter[T any](seq iter.Seq[T], pred func(T) bool) iter.Seq[T] {\n    return func(yield func(T) bool) {\n        for v := range seq {\n            if pred(v) {\n                if !yield(v) {\n                    return\n                }\n            }\n        }\n    }\n}\n\nfunc main() {\n    nums := slices.Values([]int{1, 2, 3, 4, 5, 6})\n    evens := Filter(nums, func(n int) bool { return n%2 == 0 })\n    for v := range evens {\n        fmt.Println(v) // 2, 4, 6\n    }\n}', language: 'go', fileName: 'iterators.go' }, communityIdx: 4 },
  { title: 'Why I prefer Go for backend services over Node.js', type: 'text', body: 'After 5 years of Node.js, I switched our main API to Go. The reasons: goroutines handle 100k concurrent connections with 200MB of RAM (Node needed 2GB). No event loop surprises. The standard library is batteries-included. Compilation catches errors that TypeScript misses. Deployment is a single binary. The only downside is the verbosity, but I\'ve grown to appreciate explicit error handling.', communityIdx: 4 },
  { title: 'Structured logging in Go with slog', type: 'code', codeSnippet: { code: 'package main\n\nimport (\n    "log/slog"\n    "os"\n)\n\nfunc main() {\n    logger := slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{\n        Level: slog.LevelDebug,\n    }))\n    slog.SetDefault(logger)\n\n    slog.Info("server started\",\n        \"port\", 8080,\n        \"env\", \"production\",\n    )\n\n    // With context\n    requestLogger := logger.With(\"request_id\", \"abc-123\")\n    requestLogger.Info(\"handling request\",\n        \"method\", \"GET\",\n        \"path\", \"/api/users\",\n    )\n}', language: 'go', fileName: 'logging.go' }, communityIdx: 4 },
  { title: 'Go error handling: the definitive guide for 2025', type: 'link', url: 'https://go.dev/blog/error-handling-best-practices', communityIdx: 4 },
  { title: 'Building a REST API in Go with just the standard library', type: 'text', body: 'With Go 1.22\'s enhanced routing in net/http, you no longer need chi or gorilla/mux. The new http.ServeMux supports path parameters like GET /users/{id}, method-based routing, and proper 405 Method Not Allowed responses. Combined with the encoding/json package, you can build a production-ready REST API with zero dependencies.', communityIdx: 4 },

  // react (5)
  { title: 'React Server Components finally clicked for me', type: 'text', body: 'After months of confusion, here\'s the mental model that worked: RSCs are components that run ONLY on the server. They can async/await directly, access databases, read files. They send HTML to the client, not JavaScript. Client Components are the interactive ones we\'re used to. The boundary is the "use client" directive. Think of RSCs as the new default, and Client Components as the opt-in for interactivity.', communityIdx: 5 },
  { title: 'useOptimistic hook pattern for instant UI updates', type: 'code', codeSnippet: { code: 'import { useOptimistic } from "react";\nimport { updateTodo } from "./actions";\n\nfunction TodoItem({ todo }) {\n  const [optimisticTodo, setOptimisticTodo] = useOptimistic(\n    todo,\n    (state, newComplete: boolean) => ({\n      ...state,\n      completed: newComplete,\n    })\n  );\n\n  async function toggleComplete() {\n    setOptimisticTodo(!optimisticTodo.completed);\n    await updateTodo(todo.id, !todo.completed);\n  }\n\n  return (\n    <div onClick={toggleComplete}\n         style={{ opacity: optimisticTodo.completed ? 0.5 : 1 }}>\n      {optimisticTodo.title}\n    </div>\n  );\n}', language: 'typescript', fileName: 'TodoItem.tsx' }, communityIdx: 5 },
  { title: 'Zustand vs Jotai vs Redux Toolkit: a practical comparison', type: 'text', body: 'After using all three in production:\n\n- Zustand: Best for simple to medium state. Minimal boilerplate, great DX. Use when you just need a global store.\n- Jotai: Best for fine-grained reactivity. Atom-based, similar to Recoil but simpler. Great for form state and derived computations.\n- Redux Toolkit: Best for complex state with lots of async operations. RTK Query is excellent for server state.\n\nFor most projects, Zustand + React Query covers 95% of needs.', communityIdx: 5 },
  { title: 'React 19 cheatsheet — all the new features', type: 'link', url: 'https://react.dev/blog/2024/12/05/react-19', communityIdx: 5 },
  { title: 'Custom hook: useDebounce with cleanup', type: 'code', codeSnippet: { code: 'import { useState, useEffect } from "react";\n\nexport function useDebounce<T>(value: T, delay: number): T {\n  const [debouncedValue, setDebouncedValue] = useState(value);\n\n  useEffect(() => {\n    const timer = setTimeout(() => {\n      setDebouncedValue(value);\n    }, delay);\n\n    return () => clearTimeout(timer);\n  }, [value, delay]);\n\n  return debouncedValue;\n}\n\n// Usage:\n// const [search, setSearch] = useState("");\n// const debouncedSearch = useDebounce(search, 300);\n// useEffect(() => { fetchResults(debouncedSearch); }, [debouncedSearch]);', language: 'typescript', fileName: 'useDebounce.ts' }, communityIdx: 5 },

  // webdev (6)
  { title: 'CSS :has() selector is the most powerful CSS feature in years', type: 'code', codeSnippet: { code: '/* Style parent based on child state */\n.card:has(img) {\n  grid-template-rows: 200px 1fr;\n}\n\n/* Style sibling based on another sibling */\nh2:has(+ p) {\n  margin-bottom: 0.5rem;\n}\n\n/* Form validation without JS */\nform:has(:invalid) button[type="submit"] {\n  opacity: 0.5;\n  pointer-events: none;\n}\n\n/* Dark mode based on checkbox */\nbody:has(#dark-mode:checked) {\n  --bg: #1a1a2e;\n  --text: #e0e0e0;\n}', language: 'css', fileName: 'has-selector.css' }, communityIdx: 6 },
  { title: 'Tailwind CSS v4 is a complete rewrite and it\'s 10x faster', type: 'text', body: 'Tailwind v4 dropped the PostCSS plugin architecture entirely. It now uses a custom Rust-based engine called Oxide. Build times went from 300ms to 30ms in my project. The new CSS-first config is also a massive improvement — no more tailwind.config.js. You define your theme in @theme in CSS. Plus, zero config needed for content scanning.', communityIdx: 6 },
  { title: 'The ultimate guide to web performance in 2025', type: 'link', url: 'https://web.dev/performance-2025', communityIdx: 6 },
  { title: 'HTMX is changing how I think about web apps', type: 'text', body: 'I built a full CRUD app with HTMX + Go templates and it was... refreshing. No build step, no client-side state management, no hydration issues. The server returns HTML fragments and HTMX swaps them into the DOM. For many applications, this is genuinely simpler than React/Vue/Svelte. The 14KB library handles 80% of interactive use cases.', communityIdx: 6 },
  { title: 'View Transitions API: smooth page transitions natively', type: 'code', codeSnippet: { code: '// Single page app transition\ndocument.startViewTransition(() => {\n  updateDOM();\n});\n\n// MPA transition (cross-document)\n// In CSS:\n@view-transition {\n  navigation: auto;\n}\n\n::view-transition-old(root) {\n  animation: fade-out 0.3s ease;\n}\n\n::view-transition-new(root) {\n  animation: fade-in 0.3s ease;\n}\n\n// Named transitions for specific elements\n.card {\n  view-transition-name: card-hero;\n}', language: 'css', fileName: 'view-transitions.css' }, communityIdx: 6 },

  // devops (7)
  { title: 'Docker Compose profiles changed my local dev workflow', type: 'code', codeSnippet: { code: '# docker-compose.yml\nservices:\n  api:\n    build: ./api\n    ports: [\"3000:3000\"]\n  \n  db:\n    image: postgres:16\n    profiles: [\"db\"]\n    ports: [\"5432:5432\"]\n  \n  redis:\n    image: redis:7\n    profiles: [\"cache\"]\n  \n  monitoring:\n    image: grafana/grafana\n    profiles: [\"debug\"]\n\n# Start just API + DB:\n# docker compose --profile db up\n\n# Start everything:\n# docker compose --profile db --profile cache --profile debug up', language: 'yaml', fileName: 'docker-compose.yml' }, communityIdx: 7 },
  { title: 'Kubernetes is overkill for 90% of companies', type: 'text', body: 'Hot take: if you have fewer than 50 services and fewer than 10 developers, K8s is probably slowing you down, not helping. The operational complexity, the YAML, the networking, the cost of the cluster itself. Docker Compose + a simple CI/CD pipeline + auto-scaling at the VM level covers most use cases. I\'ve seen teams spend more time maintaining K8s than writing features.', communityIdx: 7 },
  { title: 'GitHub Actions: reusable workflows cheatsheet', type: 'link', url: 'https://docs.github.com/en/actions/using-workflows/reusing-workflows', communityIdx: 7 },
  { title: 'Terraform vs Pulumi: which should you learn in 2025?', type: 'text', body: 'Both are excellent IaC tools. Terraform has a larger ecosystem and more job postings. Pulumi lets you write infrastructure in real programming languages (TypeScript, Python, Go). If you already know a programming language well, Pulumi might feel more natural. If you want maximum industry adoption and job opportunities, learn Terraform first.', communityIdx: 7 },
  { title: 'Minimal Dockerfile for a Node.js app', type: 'code', codeSnippet: { code: 'FROM node:22-slim AS base\nENV PNPM_HOME=\"/pnpm\"\nENV PATH=\"$PNPM_HOME:$PATH\"\nRUN corepack enable\n\nFROM base AS deps\nWORKDIR /app\nCOPY package.json pnpm-lock.yaml ./\nRUN --mount=type=cache,id=pnpm,target=/pnpm/store \\\n    pnpm install --frozen-lockfile --prod\n\nFROM base\nWORKDIR /app\nCOPY --from=deps /app/node_modules ./node_modules\nCOPY . .\nEXPOSE 3000\nUSER node\nCMD [\"node\", \"dist/index.js\"]', language: 'dockerfile', fileName: 'Dockerfile' }, communityIdx: 7 },

  // linux (8)
  { title: 'Nix is the package manager I always wanted', type: 'text', body: 'After years of fighting with brew, apt, and asdf, I switched to Nix. Reproducible builds, per-project dev environments with nix develop, atomic upgrades and rollbacks. The learning curve is steep but once it clicks, you\'ll never go back. I use nix flakes for all my projects now — every developer gets the exact same toolchain.', communityIdx: 8 },
  { title: 'Must-know shell aliases for productivity', type: 'code', codeSnippet: { code: '# Navigation\nalias ..="cd .."\nalias ...="cd ../.."\nalias ll="ls -alF --color=auto"\nalias la="ls -A"\n\n# Git shortcuts\nalias gs="git status"\nalias gc="git commit"\nalias gp="git push"\nalias gl="git log --oneline -20"\nalias gd="git diff"\n\n# Docker\nalias dc="docker compose"\nalias dps="docker ps --format \'table {{.Names}}\\t{{.Status}}\\t{{.Ports}}\'"\nalias dex="docker exec -it"\n\n# Safety nets\nalias rm="rm -i"\nalias cp="cp -i"\nalias mv="mv -i"', language: 'bash', fileName: '.bash_aliases' }, communityIdx: 8 },
  { title: 'Linux kernel 6.8: biggest changes explained', type: 'link', url: 'https://kernelnewbies.org/Linux_6.8', communityIdx: 8 },
  { title: 'I switched from Ubuntu to Fedora and here\'s why', type: 'text', body: 'After 10 years on Ubuntu, I made the switch. Reasons: Fedora ships newer packages (especially kernels and GNOME), uses Wayland by default and it actually works, Flatpak instead of Snap, and DNF5 is fast. The only thing I miss is the larger Ubuntu community for troubleshooting. But for development work, Fedora just feels more cutting-edge without being unstable.', communityIdx: 8 },
  { title: 'tmux config for developers', type: 'code', codeSnippet: { code: '# ~/.tmux.conf\nset -g default-terminal "tmux-256color"\nset -g mouse on\nset -g base-index 1\nset -g renumber-windows on\nset -g history-limit 50000\n\n# Better prefix\nunbind C-b\nset -g prefix C-a\nbind C-a send-prefix\n\n# Split panes with | and -\nbind | split-window -h -c \"#{pane_current_path}\"\nbind - split-window -v -c \"#{pane_current_path}\"\n\n# Vim-style pane navigation\nbind h select-pane -L\nbind j select-pane -D\nbind k select-pane -U\nbind l select-pane -R\n\n# Status bar\nset -g status-style bg=default\nset -g status-left \"#[fg=blue,bold] #S \"\nset -g status-right \"%H:%M\"', language: 'bash', fileName: '.tmux.conf' }, communityIdx: 8 },

  // git_tips (9)
  { title: 'git worktree is a hidden gem for multitasking', type: 'text', body: 'Instead of stashing or committing WIP code when you need to switch branches, use git worktree. It creates a separate working directory for a branch while keeping the same repo. `git worktree add ../feature-x feature-x` — now you have two directories, two branches, no context switching. I use this daily for code reviews and hotfixes.', communityIdx: 9 },
  { title: 'My .gitconfig for maximum productivity', type: 'code', codeSnippet: { code: '[alias]\n    s = status --short\n    co = checkout\n    br = branch\n    ci = commit\n    unstage = reset HEAD --\n    last = log -1 HEAD\n    lg = log --graph --oneline --decorate -20\n    amend = commit --amend --no-edit\n    wip = !git add -A && git commit -m \"WIP\"\n    undo = reset --soft HEAD~1\n    cleanup = !git branch --merged | grep -v main | xargs git branch -d\n\n[pull]\n    rebase = true\n\n[push]\n    autoSetupRemote = true\n\n[rerere]\n    enabled = true\n\n[diff]\n    algorithm = histogram', language: 'ini', fileName: '.gitconfig' }, communityIdx: 9 },
  { title: 'Interactive rebase tips for clean history', type: 'text', body: 'Golden rules for interactive rebase:\n1. Never rebase shared/public branches\n2. Use fixup for typo fixes: `git commit --fixup=<hash>` then `git rebase -i --autosquash`\n3. Use `git rebase -i HEAD~5` to squash WIP commits before merging\n4. Enable rerere to remember conflict resolutions\n5. Use `git reflog` as your safety net — you can always recover', communityIdx: 9 },
  { title: 'git bisect found a bug in 30 seconds', type: 'text', body: 'Had a regression somewhere in the last 200 commits. Instead of manually checking each one, I used git bisect. `git bisect start`, `git bisect bad` (current), `git bisect good v2.1.0`. Git does a binary search — I just had to say good/bad 8 times and it found the exact commit that introduced the bug. Automate it with `git bisect run npm test`.', communityIdx: 9 },
  { title: 'The best git branching strategy for small teams', type: 'link', url: 'https://trunkbaseddevelopment.com/', communityIdx: 9 },

  // databases (10)
  { title: 'PostgreSQL query optimization: EXPLAIN ANALYZE demystified', type: 'text', body: 'The most important skill for database performance is reading EXPLAIN ANALYZE output. Key things to look for: Seq Scan on large tables (add an index), Nested Loop with high actual rows (maybe a Hash Join is better), Sort with high memory usage (increase work_mem or add an index). Always look at "actual time" not "cost" — cost is an estimate, actual time is reality.', communityIdx: 10 },
  { title: 'MongoDB aggregation pipeline cheatsheet', type: 'code', codeSnippet: { code: '// Get top 5 authors by post count with their latest post\ndb.posts.aggregate([\n  { $match: { isDeleted: false } },\n  { $sort: { createdAt: -1 } },\n  { $group: {\n    _id: \"$authorUsername\",\n    postCount: { $sum: 1 },\n    totalScore: { $sum: \"$score\" },\n    latestPost: { $first: \"$title\" },\n    latestDate: { $first: \"$createdAt\" }\n  }},\n  { $sort: { postCount: -1 } },\n  { $limit: 5 },\n  { $project: {\n    author: \"$_id\",\n    postCount: 1,\n    totalScore: 1,\n    latestPost: 1,\n    _id: 0\n  }}\n]);', language: 'javascript', fileName: 'aggregation.js' }, communityIdx: 10 },
  { title: 'Redis is not just a cache — 5 patterns you should know', type: 'text', body: '1. Pub/Sub for real-time notifications\n2. Sorted Sets for leaderboards and rate limiting\n3. Streams for event sourcing and message queues\n4. HyperLogLog for counting unique visitors (12KB for billions of items)\n5. Lua scripting for atomic multi-step operations\n\nRedis is a full-fledged data structure server, not just a key-value cache.', communityIdx: 10 },
  { title: 'SQLite is all you need for most web apps', type: 'link', url: 'https://www.sqlite.org/whentouse.html', communityIdx: 10 },
  { title: 'N+1 query problem: how to detect and fix it', type: 'text', body: 'The N+1 problem: you query 1 list of items, then N individual queries for related data. Example: fetch 50 posts, then 50 separate queries for each author. Fix: use JOIN (SQL), $lookup (MongoDB), populate (Mongoose), or DataLoader (GraphQL). In ORMs, use eager loading. Tool tip: enable query logging in development to catch these early.', communityIdx: 10 },

  // algorithms (11)
  { title: 'Sliding window technique explained with 5 problems', type: 'text', body: 'The sliding window pattern works when you need to find a subarray/substring that satisfies some condition. Two pointers (left, right) define the window. Expand right to include more elements, shrink left when the window is invalid.\n\nProblems it solves:\n1. Maximum sum subarray of size K\n2. Longest substring without repeating characters\n3. Minimum window substring\n4. Fruits into baskets\n5. Longest repeating character replacement', communityIdx: 11 },
  { title: 'Binary search is not just for sorted arrays', type: 'code', codeSnippet: { code: '// Binary search on answer - find minimum capacity to ship packages in D days\nfunction shipWithinDays(weights: number[], days: number): number {\n  let lo = Math.max(...weights);\n  let hi = weights.reduce((a, b) => a + b, 0);\n  \n  while (lo < hi) {\n    const mid = Math.floor((lo + hi) / 2);\n    \n    // Can we ship all packages with capacity `mid` in `days` days?\n    let daysNeeded = 1;\n    let currentLoad = 0;\n    for (const w of weights) {\n      if (currentLoad + w > mid) {\n        daysNeeded++;\n        currentLoad = 0;\n      }\n      currentLoad += w;\n    }\n    \n    if (daysNeeded <= days) hi = mid;\n    else lo = mid + 1;\n  }\n  \n  return lo;\n}', language: 'typescript', fileName: 'binary-search-answer.ts' }, communityIdx: 11 },
  { title: 'How I went from failing LeetCode mediums to solving hards', type: 'text', body: 'It took 6 months and ~400 problems. The key was not grinding randomly but studying patterns: sliding window, two pointers, BFS/DFS, dynamic programming (1D then 2D), monotonic stack, trie, union find. For each pattern, I solved 10-15 problems sorted by difficulty. Spaced repetition helped retention. Neetcode 150 was the best starting resource.', communityIdx: 11 },
  { title: 'Visualizing common sorting algorithms', type: 'link', url: 'https://visualgo.net/en/sorting', communityIdx: 11 },
  { title: 'Trie implementation in TypeScript', type: 'code', codeSnippet: { code: 'class TrieNode {\n  children = new Map<string, TrieNode>();\n  isEnd = false;\n}\n\nclass Trie {\n  root = new TrieNode();\n\n  insert(word: string) {\n    let node = this.root;\n    for (const ch of word) {\n      if (!node.children.has(ch))\n        node.children.set(ch, new TrieNode());\n      node = node.children.get(ch)!;\n    }\n    node.isEnd = true;\n  }\n\n  search(word: string): boolean {\n    const node = this._traverse(word);\n    return node?.isEnd ?? false;\n  }\n\n  startsWith(prefix: string): boolean {\n    return this._traverse(prefix) !== null;\n  }\n\n  private _traverse(s: string): TrieNode | null {\n    let node = this.root;\n    for (const ch of s) {\n      if (!node.children.has(ch)) return null;\n      node = node.children.get(ch)!;\n    }\n    return node;\n  }\n}', language: 'typescript', fileName: 'trie.ts' }, communityIdx: 11 },

  // cpp (12)
  { title: 'C++23 std::expected is the error handling we deserved', type: 'code', codeSnippet: { code: '#include <expected>\n#include <string>\n#include <print>\n\nenum class ParseError { InvalidInput, Overflow };\n\nstd::expected<int, ParseError> parse_int(std::string_view sv) {\n    if (sv.empty()) return std::unexpected(ParseError::InvalidInput);\n    // ... parsing logic\n    return 42;\n}\n\nint main() {\n    auto result = parse_int(\"42\");\n    if (result) {\n        std::println(\"Parsed: {}\", *result);\n    } else {\n        std::println(\"Error!\");\n    }\n    \n    // Monadic operations\n    auto doubled = parse_int(\"21\")\n        .transform([](int v) { return v * 2; })\n        .value_or(0);\n}', language: 'cpp', fileName: 'expected.cpp' }, communityIdx: 12 },
  { title: 'Modern C++ project structure in 2025', type: 'text', body: 'My go-to project layout: CMake with presets, vcpkg for dependency management, clang-format + clang-tidy for code quality, GoogleTest for testing, GitHub Actions for CI. Use CMakeLists.txt at each directory level, organize headers in include/ and sources in src/. Enable all warnings: -Wall -Wextra -Wpedantic -Werror. Use sanitizers in debug builds.', communityIdx: 12 },
  { title: 'std::ranges and views make C++ feel modern', type: 'link', url: 'https://en.cppreference.com/w/cpp/ranges', communityIdx: 12 },
  { title: 'RAII pattern explained for beginners', type: 'text', body: 'RAII (Resource Acquisition Is Initialization) is the most important C++ idiom. The idea: tie resource lifetime to object lifetime. When the object is constructed, acquire the resource. When it\'s destructed, release it. This is why we use unique_ptr instead of raw new/delete, fstream instead of fopen/fclose, lock_guard instead of manual lock/unlock. Stack unwinding guarantees cleanup even when exceptions are thrown.', communityIdx: 12 },
  { title: 'Compile-time string parsing with constexpr', type: 'code', codeSnippet: { code: '#include <array>\n#include <string_view>\n\nconstexpr auto split(std::string_view sv, char delim) {\n    std::array<std::string_view, 10> result{};\n    size_t count = 0;\n    size_t start = 0;\n    \n    for (size_t i = 0; i <= sv.size(); ++i) {\n        if (i == sv.size() || sv[i] == delim) {\n            result[count++] = sv.substr(start, i - start);\n            start = i + 1;\n        }\n    }\n    return std::pair{result, count};\n}\n\n// Parsed at compile time!\nconstexpr auto [parts, n] = split(\"hello,world,cpp\", \',\');\nstatic_assert(n == 3);\nstatic_assert(parts[0] == \"hello\");', language: 'cpp', fileName: 'constexpr_split.cpp' }, communityIdx: 12 },

  // java (13)
  { title: 'Virtual threads in Java 21 are production ready', type: 'text', body: 'We migrated our Spring Boot API from platform threads to virtual threads. Result: throughput increased 4x under high load, memory usage dropped 60%. The migration was trivial — just set spring.threads.virtual.enabled=true in application.properties. Virtual threads make blocking I/O efficient without the complexity of reactive programming. No more WebFlux spaghetti!', communityIdx: 13 },
  { title: 'Record patterns + sealed interfaces = exhaustive matching', type: 'code', codeSnippet: { code: 'sealed interface Shape permits Circle, Rectangle, Triangle {}\nrecord Circle(double radius) implements Shape {}\nrecord Rectangle(double w, double h) implements Shape {}\nrecord Triangle(double a, double b, double c) implements Shape {}\n\n// Exhaustive pattern matching with deconstruction\ndouble area(Shape shape) {\n    return switch (shape) {\n        case Circle(var r) -> Math.PI * r * r;\n        case Rectangle(var w, var h) -> w * h;\n        case Triangle(var a, var b, var c) -> {\n            var s = (a + b + c) / 2;\n            yield Math.sqrt(s * (s-a) * (s-b) * (s-c));\n        }\n    }; // No default needed — compiler knows it\'s exhaustive!\n}', language: 'java', fileName: 'Shape.java' }, communityIdx: 13 },
  { title: 'Spring Boot 3.3 release notes', type: 'link', url: 'https://spring.io/blog/2024/spring-boot-3-3', communityIdx: 13 },
  { title: 'Why Java is still the best language for enterprise backends', type: 'text', body: 'Controversial opinion: Java in 2025 is a great language. Records, sealed classes, pattern matching, virtual threads, and the upcoming value types make it modern and expressive. The JVM is the most optimized runtime in existence. The ecosystem is unmatched: Spring, Hibernate, Kafka, Elasticsearch all have first-class Java support. Hiring is easy. Libraries are battle-tested.', communityIdx: 13 },
  { title: 'Testcontainers: integration tests with real databases', type: 'code', codeSnippet: { code: '@SpringBootTest\n@Testcontainers\nclass UserRepositoryTest {\n    \n    @Container\n    static PostgreSQLContainer<?> postgres = \n        new PostgreSQLContainer<>(\"postgres:16\")\n            .withDatabaseName(\"test\")\n            .withUsername(\"test\")\n            .withPassword(\"test\");\n    \n    @DynamicPropertySource\n    static void configureProperties(DynamicPropertyRegistry registry) {\n        registry.add(\"spring.datasource.url\", postgres::getJdbcUrl);\n        registry.add(\"spring.datasource.username\", postgres::getUsername);\n        registry.add(\"spring.datasource.password\", postgres::getPassword);\n    }\n    \n    @Autowired\n    UserRepository userRepository;\n    \n    @Test\n    void shouldSaveAndFindUser() {\n        var user = new User(\"alice\", \"alice@test.com\");\n        userRepository.save(user);\n        \n        var found = userRepository.findByUsername(\"alice\");\n        assertThat(found).isPresent();\n    }\n}', language: 'java', fileName: 'UserRepositoryTest.java' }, communityIdx: 13 },

  // machinelearning (14)
  { title: 'Fine-tuning Llama 3 on a single GPU with QLoRA', type: 'text', body: 'You don\'t need a cluster to fine-tune LLMs. With QLoRA (4-bit quantization + LoRA adapters), I fine-tuned Llama 3 8B on a single RTX 4090. Training took 4 hours on 10K examples. The key: use bitsandbytes for 4-bit loading, PEFT for LoRA, and the SFTTrainer from trl. Total VRAM usage: 18GB. The model quality is surprisingly close to full fine-tuning.', communityIdx: 14 },
  { title: 'PyTorch Lightning training loop template', type: 'code', codeSnippet: { code: 'import pytorch_lightning as pl\nimport torch\nfrom torch import nn\n\nclass TextClassifier(pl.LightningModule):\n    def __init__(self, vocab_size, embed_dim, num_classes, lr=1e-3):\n        super().__init__()\n        self.save_hyperparameters()\n        self.embedding = nn.Embedding(vocab_size, embed_dim)\n        self.classifier = nn.Sequential(\n            nn.Linear(embed_dim, 128),\n            nn.ReLU(),\n            nn.Dropout(0.3),\n            nn.Linear(128, num_classes)\n        )\n        self.loss_fn = nn.CrossEntropyLoss()\n    \n    def forward(self, x):\n        x = self.embedding(x).mean(dim=1)\n        return self.classifier(x)\n    \n    def training_step(self, batch, batch_idx):\n        x, y = batch\n        logits = self(x)\n        loss = self.loss_fn(logits, y)\n        self.log(\"train_loss\", loss)\n        return loss\n    \n    def configure_optimizers(self):\n        return torch.optim.AdamW(\n            self.parameters(), lr=self.hparams.lr\n        )', language: 'python', fileName: 'classifier.py' }, communityIdx: 14 },
  { title: 'Attention is all you need — paper explained simply', type: 'link', url: 'https://arxiv.org/abs/1706.03762', communityIdx: 14 },
  { title: 'RAG vs fine-tuning: when to use which for LLMs', type: 'text', body: 'Rule of thumb:\n- RAG when you need the model to access dynamic/up-to-date information, or when you have a large knowledge base\n- Fine-tuning when you need the model to learn a specific style, format, or domain-specific reasoning\n- Both when you need domain knowledge AND specific output format\n\nRAG is cheaper, easier to update, and more controllable. Fine-tuning gives better quality for specific tasks but is expensive and hard to keep current.', communityIdx: 14 },
  { title: 'The batch size matters more than you think', type: 'text', body: 'Large batch sizes converge faster but generalize worse. Small batch sizes add noise that acts as regularization. The sweet spot depends on your problem. Rule of thumb: start with 32, double until validation loss stops improving. For LLMs, use gradient accumulation to simulate large batches on limited VRAM. Learning rate should scale linearly with batch size.', communityIdx: 14 },

  // security (15)
  { title: 'JWT security best practices for 2025', type: 'text', body: 'Common JWT mistakes I see in code reviews:\n1. Storing JWTs in localStorage (XSS vulnerable) — use HttpOnly cookies\n2. Not validating the algorithm — always specify allowed algorithms\n3. Long-lived access tokens — keep them short (15 min), use refresh tokens\n4. Not checking token expiry on the server side\n5. Putting sensitive data in the payload — JWTs are base64, not encrypted\n6. Not rotating signing keys regularly', communityIdx: 15 },
  { title: 'SQL injection is still the #1 vulnerability in 2025', type: 'code', codeSnippet: { code: '-- ❌ VULNERABLE: string concatenation\nconst query = `SELECT * FROM users WHERE id = ${req.params.id}`;\n-- Attacker sends: 1; DROP TABLE users; --\n\n-- ✅ SAFE: parameterized queries\nconst query = \'SELECT * FROM users WHERE id = $1\';\nconst result = await db.query(query, [req.params.id]);\n\n-- ✅ SAFE: using an ORM\nconst user = await User.findByPk(req.params.id);\n\n-- ✅ SAFE: prepared statements\nconst stmt = db.prepare(\'SELECT * FROM users WHERE id = ?\');\nconst user = stmt.get(req.params.id);', language: 'sql', fileName: 'sql-injection.sql' }, communityIdx: 15 },
  { title: 'OWASP Top 10 2025: what changed', type: 'link', url: 'https://owasp.org/Top10/', communityIdx: 15 },
  { title: 'How I found an XSS vulnerability in a popular React library', type: 'text', body: 'The library was using dangerouslySetInnerHTML with user input that went through a "sanitizer" that only stripped <script> tags. But you can execute JavaScript without script tags: <img onerror="alert(1)">, <svg onload="...">, even CSS expression(). The fix was switching to DOMPurify. Lesson: never write your own HTML sanitizer. Use DOMPurify or sanitize-html.', communityIdx: 15 },
  { title: 'Rate limiting implementation with sliding window', type: 'code', codeSnippet: { code: 'import Redis from "ioredis";\n\nconst redis = new Redis();\n\nasync function slidingWindowRateLimit(\n  key: string,\n  limit: number,\n  windowMs: number\n): Promise<boolean> {\n  const now = Date.now();\n  const windowStart = now - windowMs;\n  \n  const pipeline = redis.pipeline();\n  // Remove old entries\n  pipeline.zremrangebyscore(key, 0, windowStart);\n  // Add current request\n  pipeline.zadd(key, now, `${now}-${Math.random()}`);\n  // Count requests in window\n  pipeline.zcard(key);\n  // Set expiry\n  pipeline.expire(key, Math.ceil(windowMs / 1000));\n  \n  const results = await pipeline.exec();\n  const count = results![2][1] as number;\n  \n  return count <= limit;\n}', language: 'typescript', fileName: 'rate-limiter.ts' }, communityIdx: 15 },

  // opensource (16)
  { title: 'How to write a good README for your open source project', type: 'text', body: 'A good README has:\n1. One-line description of what it does\n2. Screenshot or demo GIF\n3. Quick install command (copy-pasteable)\n4. Minimal "getting started" example\n5. API reference or link to docs\n6. Contributing guidelines link\n7. License badge\n\nSkip: long history sections, excessive badges, walls of text before the install command. People want to know what it does and how to use it in 30 seconds.', communityIdx: 16 },
  { title: 'My first open source contribution: a guide for beginners', type: 'link', url: 'https://opensource.guide/how-to-contribute/', communityIdx: 16 },
  { title: 'Semantic versioning is a social contract, not a technical one', type: 'text', body: 'SemVer doesn\'t tell you about the size of changes — it tells you about compatibility. MAJOR: your users\' code might break. MINOR: new features, nothing breaks. PATCH: bug fixes, nothing breaks. The hardest part isn\'t the numbering, it\'s deciding what counts as a breaking change. A security fix that changes behavior? A bug fix that people depended on? These are judgment calls.', communityIdx: 16 },
  { title: 'Why I mass-deleted my GitHub stars', type: 'text', body: 'I had 2000+ starred repos. I never looked at them. Stars are bookmarks you never read. Instead, I now use GitHub Lists to categorize repos I actually use, and I maintain a personal awesome-list markdown file in a private repo. Much more useful than a giant unsorted star list.', communityIdx: 16 },
  { title: 'License comparison for devs: MIT vs Apache 2.0 vs GPL', type: 'text', body: 'Quick guide:\n- MIT: Do whatever you want, just keep the copyright notice. Simplest, most permissive.\n- Apache 2.0: Like MIT but with patent protection. Use this if patents are a concern.\n- GPL: Copyleft — derivative works must also be GPL. Protects software freedom but scares away some companies.\n- AGPL: Like GPL but also covers network use (SaaS).\n\nFor libraries: MIT or Apache 2.0. For applications: GPL if you want to enforce openness. For SaaS: consider AGPL.', communityIdx: 16 },

  // career (17)
  { title: 'How I passed FAANG interviews after 3 months of prep', type: 'text', body: 'My prep strategy:\n- Month 1: Neetcode 150 (focused on patterns, not memorization)\n- Month 2: System design (Designing Data-Intensive Applications + mock interviews)\n- Month 3: Behavioral stories (STAR method, 10 stories covering leadership, conflict, failure)\n\nThe secret nobody tells you: communication matters as much as the solution. Explain your thought process, ask clarifying questions, discuss trade-offs. A brute force solution with great communication beats an optimal solution with silence.', communityIdx: 17 },
  { title: 'Salary negotiation tips for software engineers', type: 'text', body: 'Rules I follow:\n1. Never give the first number\n2. Always negotiate — they expect it\n3. Use competing offers as leverage (even if you prefer one company)\n4. Negotiate total comp, not just base (RSUs, signing bonus, WFH stipend)\n5. Get everything in writing\n6. Be professional and enthusiastic — they want you, that\'s why they made an offer\n\nThe 5 minutes of discomfort during negotiation can be worth $10-50K over the lifetime of the role.', communityIdx: 17 },
  { title: 'The tech job market in 2025: my observations', type: 'text', body: 'After helping 50+ engineers with their job search this year: junior roles are still competitive, but mid-level and senior roles have rebounded significantly. AI/ML roles are white-hot. Remote is less common than 2022 but still available. The biggest differentiator is no longer LeetCode — it\'s system design and actual project experience. Side projects and open source contributions genuinely help.', communityIdx: 17 },
  { title: 'Remote work toolkit: tools I use daily', type: 'link', url: 'https://remote.tools/', communityIdx: 17 },
  { title: 'Should you specialize or be a generalist in 2025?', type: 'text', body: 'The best career strategy is a T-shape: deep expertise in one area (the vertical bar) and broad knowledge across many (the horizontal bar). Specialize enough to be the go-to person for something specific (e.g., database optimization, accessibility, distributed systems). But stay broad enough to understand the full stack and collaborate effectively with other specialists.', communityIdx: 17 },

  // vim_emacs (18)
  { title: 'Neovim setup that replaced my VS Code', type: 'text', body: 'After 2 years of tweaking, my Neovim config is faster and more capable than VS Code was. Key plugins: lazy.nvim (package manager), telescope.nvim (fuzzy finder), nvim-lspconfig + mason (LSP), nvim-cmp (completions), treesitter (syntax highlighting), gitsigns (git integration), which-key (keybind help). Total startup time: 50ms. VS Code was 3 seconds.', communityIdx: 18 },
  { title: 'Vim motions cheatsheet for beginners', type: 'code', codeSnippet: { code: '# Essential motions\nw/b     - word forward/backward\ne       - end of word\n0/$     - start/end of line\ngg/G    - start/end of file\nf{char} - jump to char on line\n%       - matching bracket\n\n# Text objects (use with d, c, y, v)\ndiw     - delete inner word\nci\"     - change inside quotes\nda(     - delete around parentheses\nyap     - yank around paragraph\n\n# Powerful combos\ndt)     - delete until )\nct\"     - change until \"\nJ       - join lines\n.       - repeat last command\n\n# Registers\n\"ayy    - yank line into register a\n\"ap     - paste from register a\n\"0p     - paste last yank (not delete)', language: 'markdown', fileName: 'vim-cheatsheet.md' }, communityIdx: 18 },
  { title: 'The Vim vs Emacs debate is dead — use what makes you productive', type: 'text', body: 'I use Neovim with vim motions for text editing and Emacs with evil-mode for org-mode and Magit (best Git interface ever made). The real answer is: the best editor is the one you know deeply. Learn the keybinds, learn the plugin ecosystem, customize it for your workflow. Spending time learning your tools pays compound interest.', communityIdx: 18 },
  { title: 'Emacs org-mode is the best productivity tool ever made', type: 'link', url: 'https://orgmode.org/', communityIdx: 18 },
  { title: 'Neovim Lua config from scratch', type: 'code', codeSnippet: { code: '-- init.lua\nvim.g.mapleader = \" \"\n\n-- Options\nvim.opt.number = true\nvim.opt.relativenumber = true\nvim.opt.tabstop = 2\nvim.opt.shiftwidth = 2\nvim.opt.expandtab = true\nvim.opt.smartindent = true\nvim.opt.termguicolors = true\nvim.opt.signcolumn = \"yes\"\nvim.opt.clipboard = \"unnamedplus\"\n\n-- Keymaps\nlocal map = vim.keymap.set\nmap(\"n\", \"<leader>w\", \":w<CR>\")\nmap(\"n\", \"<leader>q\", \":q<CR>\")\nmap(\"n\", \"<leader>ff\", \":Telescope find_files<CR>\")\nmap(\"n\", \"<leader>fg\", \":Telescope live_grep<CR>\")\nmap(\"n\", \"<leader>e\", \":NvimTreeToggle<CR>\")\n\n-- Better window navigation\nmap(\"n\", \"<C-h>\", \"<C-w>h\")\nmap(\"n\", \"<C-j>\", \"<C-w>j\")\nmap(\"n\", \"<C-k>\", \"<C-w>k\")\nmap(\"n\", \"<C-l>\", \"<C-w>l\")', language: 'lua', fileName: 'init.lua' }, communityIdx: 18 },

  // mobile_dev (19)
  { title: 'React Native vs Flutter in 2025: which should you choose?', type: 'text', body: 'After building production apps with both:\n\nReact Native: Better if your team knows React/JS. Hot reload is faster. Expo makes development amazing. The bridge to native is seamless. New Architecture (Fabric + TurboModules) fixed the performance gap.\n\nFlutter: Better for pixel-perfect custom UIs. Dart is a nice language. Hot reload is great. But the ecosystem is smaller and hiring Dart developers is harder.\n\nMy pick: React Native with Expo for most teams.', communityIdx: 19 },
  { title: 'Expo Router: file-based routing for React Native', type: 'code', codeSnippet: { code: '// app/(tabs)/_layout.tsx\nimport { Tabs } from \"expo-router\";\nimport { Home, Search, User } from \"lucide-react-native\";\n\nexport default function TabLayout() {\n  return (\n    <Tabs screenOptions={{ headerShown: false }}>\n      <Tabs.Screen\n        name=\"index\"\n        options={{\n          title: \"Home\",\n          tabBarIcon: ({ color }) => <Home color={color} />,\n        }}\n      />\n      <Tabs.Screen\n        name=\"search\"\n        options={{\n          title: \"Search\",\n          tabBarIcon: ({ color }) => <Search color={color} />,\n        }}\n      />\n      <Tabs.Screen\n        name=\"profile\"\n        options={{\n          title: \"Profile\",\n          tabBarIcon: ({ color }) => <User color={color} />,\n        }}\n      />\n    </Tabs>\n  );\n}', language: 'typescript', fileName: '_layout.tsx' }, communityIdx: 19 },
  { title: 'SwiftUI is finally mature enough for production', type: 'text', body: 'SwiftUI in its early days was rough — missing features, performance issues, and bugs. But as of iOS 17/18, it\'s genuinely production-ready. NavigationStack works properly, custom layouts are powerful, and the declarative syntax is a joy. I still drop into UIKit for complex collection views, but 90% of my UI is SwiftUI now.', communityIdx: 19 },
  { title: 'Jetpack Compose best practices', type: 'link', url: 'https://developer.android.com/develop/ui/compose/practices', communityIdx: 19 },
  { title: 'Mobile app architecture: MVI pattern explained', type: 'text', body: 'MVI (Model-View-Intent) is the cleanest mobile architecture pattern I\'ve used. Intent = user actions (events). Model = immutable state (single source of truth). View = renders state. The unidirectional data flow makes debugging trivial — every state change is traceable. Works great with Compose, SwiftUI, and React Native. Combine with a state machine for complex flows.', communityIdx: 19 },
];

async function seed() {
  console.log('Connecting to MongoDB...');
  await mongoose.connect(env.MONGODB_URI);
  console.log('Connected.');

  // Clear existing data
  console.log('Clearing existing data...');
  await Promise.all([
    User.deleteMany({}),
    Community.deleteMany({}),
    Post.deleteMany({}),
  ]);

  // Create user
  console.log('Creating user...');
  const user = await User.create({
    username: 'devmaster',
    email: 'devmaster@devhub.dev',
    passwordHash: 'Password123!',
    displayName: 'Dev Master',
    bio: 'Full-stack developer | Open source enthusiast | Building things that matter',
    karma: 0,
    postKarma: 0,
    commentKarma: 0,
    joinedCommunities: [],
  });

  // Create communities
  console.log('Creating 20 communities...');
  const communityDocs = [];
  for (const c of COMMUNITIES) {
    const community = await Community.create({
      ...c,
      creator: user._id,
      moderators: [user._id],
      memberCount: 1,
      postCount: 0,
    });
    communityDocs.push(community);
    user.joinedCommunities.push(community._id);
  }
  await user.save();

  // Create posts with varying scores and timestamps
  console.log('Creating 100 posts...');
  const now = Date.now();
  for (let i = 0; i < POSTS.length; i++) {
    const p = POSTS[i];
    const community = communityDocs[p.communityIdx];

    // Vary timestamps: spread across last 30 days
    const ageMs = Math.random() * 30 * 24 * 60 * 60 * 1000;
    const createdAt = new Date(now - ageMs);

    // Random scores
    const upvoteCount = Math.floor(Math.random() * 200) + 1;
    const downvoteCount = Math.floor(Math.random() * 20);
    const score = upvoteCount - downvoteCount;
    const hotScore = calculateHotScore(score, createdAt);

    const postData: any = {
      title: p.title,
      type: p.type,
      author: user._id,
      community: community._id,
      authorUsername: user.username,
      communityName: community.name,
      upvoteCount,
      downvoteCount,
      score,
      hotScore,
      commentCount: Math.floor(Math.random() * 50),
      createdAt,
      updatedAt: createdAt,
    };

    if (p.type === 'text' && p.body) postData.body = p.body;
    if (p.type === 'link' && p.url) postData.url = p.url;
    if (p.type === 'code' && p.codeSnippet) postData.codeSnippet = p.codeSnippet;

    await Post.create(postData);

    // Update community post count
    await Community.findByIdAndUpdate(community._id, { $inc: { postCount: 1 } });
  }

  // Update user karma
  const totalKarma = POSTS.length * 50; // approximate
  await User.findByIdAndUpdate(user._id, {
    karma: totalKarma,
    postKarma: totalKarma,
  });

  console.log('\nSeed complete!');
  console.log(`  User: devmaster / Password123!`);
  console.log(`  Communities: ${COMMUNITIES.length}`);
  console.log(`  Posts: ${POSTS.length}`);

  await mongoose.connection.close();
  console.log('MongoDB connection closed.');
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
